name: services

on:
  push:
    branches:
      - main

jobs:
  proyecto:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Correr la app con Gunicorn en segundo plano
      run: |
        gunicorn -b 0.0.0.0:5000 app:app &

    - name: Exponer la app con ngrok
      run: |
        pip install pyngrok
        ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        nohup ngrok http 5000 &  # Ejecutar ngrok en segundo plano

    - name: Mostrar la URL de ngrok
      run: |
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Mantener el contenedor activo
      run: |
        sleep 3600  # Mantiene el contenedor activo por 1 hora
        